### ISSUE TITLE
Add github action 

### ISSUE THREAD

**Issue by Borber** [BurtonQin/lockbud#48]
Add a github action yml configuration, so that it can be automatically checked after each code commit.

**Comment by bxb100** [comment]
I like this idea, if @BurtonQin starts to do I can help.

**Comment by BurtonQin** [comment]
I am learning how to deploy github action.

**Comment by bxb100** [comment]
What's you prefer:
* using docker with night toolchain so that we don't need set night toolchain in the step
* using `rustup toolchain install nightly` and checkout this repo installed then `cargo +nightly lockbud`

and more:
* https://github.com/actions-rs/clippy-check This is an action with GitHub check annotation[^1]
* https://github.com/xd009642/tarpaulin they use docker to maintain env

[^1]: https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#list-check-run-annotations

**Comment by ComAirProject** [comment]
@bxb100 I am still new to Github action and I am trying to add the Github action in branch `action`. Could you please help check it?

**Comment by bxb100** [comment]
@ComAirProject Ye, I push a draft, you can see https://github.com/BurtonQin/lockbud/pull/49
