### ISSUE TITLE
Why is `cargo clean` needed to run lockbud?

### ISSUE THREAD

**Issue by zjp-CN** [BurtonQin/lockbud#63]
I'm aware of some information emitted from cargo will be cached and never be seen twice.

But I guess lockbud is using MIR the output of which can be dumped as files, so no need to clean the cargo caches.

For some projects where there are dozens of packages in a workspace, `cargo clean` will largely increase the duration of total checking time, since each package will be compiled from scratch, losing the benifits of cargo caches.

**Comment by BurtonQin** [comment]
Thx for your suggestions. Note that MIR files are more unstable than MIR internal APIs. l have not find any libraries that can parse MIR files. Relying on the MIR internal APIs seems to be the only choice for now.

lockbud works as an extension of `cargo build` and Rust's incremental build system also applies to lockbud. lockbud will not check the unmodified code since the compiler does not rebuild it. That's why lockbud requires `cargo clean` in between two `cargo build`s. To solve it I will look into the incremental building flags in Rustc and provide an option for lockbud to stop incremental building.

**Comment by zjp-CN** [comment]
Thank you for the explanation. I'm interested in and working on integrating lockbud into [os-checker](https://github.com/os-checker/os-checker), a tool to run checkers for Rust projects and present the statistics and results in WebUI.

So I'm not asking for new features to cope with incremental buildings LOL. Instead, os-checker won't modify source code, so I think lockbud can work well here. 😄 

I may have some more questions about lockbud. Would you mind if I contact with you in personal emails to elaborate they in Chinese?

**Comment by BurtonQin** [comment]
No problem. Just email me in Chinese. bobbqqin@gmail.com
