### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by gdesmott** [BurtonQin/lockbud#73]
To reproduce you'll need to install GStreamer dev packages such as `gstreamer1-devel gstreamer1-plugins-base-devel` on Fedora. Then run:

```
> git clone https://gitlab.freedesktop.org/gdesmott/gst-plugins-rs.git --branch lockbud-bug
> cd gst-plugins-rs/utils/togglerecord/
> cargo +nightly-2024-10-05 lockbud
```

`lockbud` will keep running forever eating memory.

**Comment by BurtonQin** [comment]
I have successfully reproduced this bug on my machine.
The reason, to my surprise, is due to a bug in petgraph:
https://github.com/BurtonQin/lockbud/blob/0a31a3141e7f144558058189ec7a00bd4a0aeade/src/detector/lock/mod.rs#L909C17-L910C35
```
            let cycle_paths =
                algo::all_simple_paths::<Vec<_>, _>(&self.graph, target, src, 0, None)
                    .collect::<Vec<_>>();
```
The call to `all_simple_paths` will get stuck forever.
I am trying to figure out how to fix it.

**Comment by BurtonQin** [comment]
petgraph::algo::all_simple_paths may return infinite number of paths.
I have reported it to petgraph in https://github.com/petgraph/petgraph/issues/680.
I use a workaround to add a limit to the number of paths taken. The infinite loop bug no longer appear on my machine.
Feel free to check if it works for you.

**Comment by gdesmott** [comment]
That works for me as well. Thanks for the workaround!
